# ADaM YAML Specification Schema
# Defines the structure and validation rules for ADaM YAML specifications

specification:
  type: object
  required:
    - columns
  properties:
    domain:
      type: string
      description: ADaM domain name (e.g., ADSL, ADAE)
      pattern: "^AD[A-Z]+$"
      
    key:
      type: array
      description: Key variables for the dataset
      items:
        type: string
      min_items: 1
      unique_items: true
      
    config:
      type: array
      description: Configuration files to inherit from
      items:
        one_of:
          - type: string
          - type: object
          
    columns:
      type: array
      description: Column specifications
      items:
        $ref: "#/definitions/column"

definitions:
  column:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: Variable name
        pattern: "^[A-Z][A-Z0-9_]*$"
        
      label:
        type: string
        description: Variable label
        max_length: 200
        
      type:
        type: string
        description: Data type
        enum:
          - str
          - int
          - float
          - date
          - datetime
          - bool
          
      core:
        type: string
        description: Core status
        enum:
          - cdisc-required
          - company-required
          - optional
          - conditional
          
      drop:
        type: boolean
        description: Flag to drop this variable from parent config
        default: false
        
      derivation:
        $ref: "#/definitions/derivation"
        
      validation:
        $ref: "#/definitions/validation"
        
  derivation:
    type: object
    description: Derivation rules for the variable
    properties:
      source:
        type: string
        description: Source dataset.variable
        pattern: "^[A-Z]+\\.[A-Z][A-Z0-9_]*$"
        
      constant:
        description: Constant value
        
      filter:
        type: string
        description: Filter condition (Python-like expression)
        
      function:
        type: string
        description: Function name to apply
        
      height:
        type: string
        description: Height variable for BMI calculation
        
      weight:
        type: string
        description: Weight variable for BMI calculation
        
      join:
        type: object
        description: Join specification
        properties:
          dataset:
            type: string
          on:
            type: array
            items:
              type: string
          type:
            type: string
            enum:
              - left
              - right
              - inner
              - outer
              
      expression:
        type: string
        description: Python expression for derivation
        
  validation:
    type: object
    description: Validation rules for the variable
    properties:
      maximum_missing_percentage:
        type: number
        minimum: 0
        maximum: 100
        description: Maximum allowed percentage of missing values
        
      allowed_values:
        type: array
        description: List of allowed values
        unique_items: true
        
      min:
        type: number
        description: Minimum value
        
      max:
        type: number
        description: Maximum value
        
      unique:
        type: boolean
        description: Values must be unique
        
      pattern:
        type: string
        description: Regular expression pattern
        
      not_null:
        type: boolean
        description: Value cannot be null
        
      length:
        type: object
        description: String length constraints
        properties:
          min:
            type: integer
            minimum: 0
          max:
            type: integer
            minimum: 0